name: Starplat CI

on:
  push:
    branches: [ "**" ]  # This will run on all branches
  pull_request:
    branches: [ "**" ]  # This will run on pull requests to all branches

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Starplat
      run: |
        cd src
        make

    - name: Check if executable exists
      run: |
        if [ -f src/starplat ]; then
          echo "Starplat executable built successfully"
        else
          echo "Starplat executable not found"
          exit 1
        fi
